[package]
name = "gate"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gate"
path = "src/main.rs"

[dependencies]
actix-web = "4.14.0"
actix-ws = "0.4.0"
actix-files = "0.6.10"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
hmac = "0.13.0"
sha2 = "0.11.0"
hex = "0.4.3"
rand = "0.8"
hickory-resolver = "0.24"
futures-util = "0.3"
log = "0.4"
env_logger = "0.11"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
chrono-tz = "0.9"
percent-encoding = "2.3.2"

[profile.release]
opt-level = 3
lto = true
